### ISSUE TITLE
recursion error

### ISSUE THREAD

**Issue by mofirojean** [mofirojean/25-Coding-Challenge-Part-I#12]
After running the code in challenge 45 using the language python 
I received an error message 

RecursionError: maximum recursion depth exceeded while calling a Python object

Here is an image of the problem 
![Screenshot from 2022-09-26 15-05-56](https://user-images.githubusercontent.com/93985482/192298257-c078309d-dfb0-44c9-bb95-7ffe35848ae6.png)

**Comment by techsnap** [comment]
Hey @mofirojean, this is happening because there is a typo on line 10: `ar = sumArray(arr)`
It should instead be `ar = sumArray(ar)`

You should rename `ar` variable to avoid confusing it with `arr`.

**Comment by mofirojean** [comment]
thanks bro for the correction
